# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7c374a9c79e761da3cc2cb76fcc87273caa2928371a264e134ab612e0af15267181a8fb34ac2f2f25dddcbef6ff83c89b25963901b7b3cd5bb4852851c7caf8d

test:
  secret_key_base: d05d8ccf373e5adf2887b137c7aee29eff744667630fcf779511656fc9f68f822a6b08e963fca52b4facac6c45a9476538829e0614f1eb10cf07eae613c60f27

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
